//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM2_OID
    {
        public string OID { get; set; }
        public int ORG_ID { get; set; }
        public string PARENT_OID { get; set; }
        public string COMPANY { get; set; }
        public string COMPANY_CODE { get; set; }
        public string POSTCODE { get; set; }
        public string ADDR_FULL { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string DN { get; set; }
        public string ENG_NAME { get; set; }
        public string URL { get; set; }
        public string OID_TYPE_ID { get; set; }
        public string SOURCE_FROM { get; set; }
        public string IS_VALID { get; set; }
        public string CREATED_USER { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
