//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM2_DIS_MAP_RESOURCE
    {
        public string DIS_TYPE_D { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
        public string DIS_TYPE_M_NAME { get; set; }
        public string DIS_TYPE_D_NAME { get; set; }
        public string RESOURCE_NAME { get; set; }
    }
}
