//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM2_CASE_INFO
    {
        public string EOC_ID { get; set; }
        public string PRJ_NO { get; set; }
        public string CASE_NO { get; set; }
        public System.DateTime CASE_TIME { get; set; }
        public string CITY_ID { get; set; }
        public string TOWN_ID { get; set; }
        public string VILLAGE_ID { get; set; }
        public string CASE_LOCATION { get; set; }
        public string DIS_TYPE_M { get; set; }
        public string DIS_TYPE_D { get; set; }
        public string CASE_SCALE { get; set; }
        public string IS_CASE_SERIOUS { get; set; }
        public string IS_TRAFHINDER { get; set; }
        public string IS_ROADBLOCK { get; set; }
        public decimal FLOODING_LENGTH { get; set; }
        public decimal FLOODING_WIDTH { get; set; }
        public decimal FLOODING_DEPTH { get; set; }
        public decimal FLOODING_AREA { get; set; }
        public string BUILDING_USE_M { get; set; }
        public string BUILDING_USE_D { get; set; }
        public string BUILDING_TYPE { get; set; }
        public string BUILDING_OTHER_NAME { get; set; }
        public int BUILDING_AREA { get; set; }
        public int BUILDING_ABOVE_FLOOR { get; set; }
        public int BUILDING_UNDER_FLOOR { get; set; }
        public string DIS_RISK_NAME { get; set; }
        public string DIS_RISK_SUPPORT { get; set; }
        public string CASE_DESC { get; set; }
        public string CLOSE_STATUS { get; set; }
        public string CASE_COORDINATE_TYPE { get; set; }
        public string CASE_TWD97_PTS { get; set; }
        public string CASE_WGS84_PTS { get; set; }
        public string REPORT_LOCATION { get; set; }
        public string REPORT_COORDINATE_TYPE { get; set; }
        public string REPORT_TWD97_PTS { get; set; }
        public string REPORT_WGS84_PTS { get; set; }
        public int INJURED_NUM { get; set; }
        public int DEAD_NUM { get; set; }
        public int LOSTCON_NUM { get; set; }
        public string IS_TRAPPED { get; set; }
        public int TRAPPED_NUM { get; set; }
        public int TRAPPED_NLIFE_NUM { get; set; }
        public string IS_TRAPPED_UNKNOW { get; set; }
        public string TRAPPED_PLACE { get; set; }
        public int SHELTER_NUMBER { get; set; }
        public int HOUSE_DAMAGE_NUM { get; set; }
        public int PROPERTY_LOSS_NUM { get; set; }
        public string IS_PEOPLE_REPORT { get; set; }
        public string PEOPLE_USER_NAME { get; set; }
        public string PEOPLE_TEL { get; set; }
        public string DIS_NOTIFY_TYPE { get; set; }
        public string REPORT_USER { get; set; }
        public string REPORT_USER_NAME { get; set; }
        public string REPORT_UNIT { get; set; }
        public string REPORT_TEL { get; set; }
        public string REPORT_MOBILE { get; set; }
        public string DIS_RELIEF_TYPE_NAME { get; set; }
        public string DIS_RELIEF_CITY_ID { get; set; }
        public string DIS_RELIEF_STEL { get; set; }
        public Nullable<System.DateTime> ACCEPT_TIME { get; set; }
        public Nullable<System.DateTime> LAST_EDIT_TIME { get; set; }
        public string COMBINE_CASE_NO { get; set; }
        public string IS_COMBINE_MAIN { get; set; }
        public string IS_COMBINE_CASE { get; set; }
        public string CASE_HANDLING_TYPE { get; set; }
        public string CASE_STATUS { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
