//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM2_CASE_INJURE_INFO
    {
        public string EOC_ID { get; set; }
        public string PRJ_NO { get; set; }
        public string CASE_NO { get; set; }
        public string CASE_RENEW_ID { get; set; }
        public string CAS_ID { get; set; }
        public string CAS_USER_NAME { get; set; }
        public Nullable<decimal> CAS_USER_AGE { get; set; }
        public string CAS_USER_SEX { get; set; }
        public Nullable<System.DateTime> CAS_TIME { get; set; }
        public string CAS_REASON { get; set; }
        public string CAS_HOSPITAL { get; set; }
        public string CAS_ADDRESS { get; set; }
        public string CAS_TYPE { get; set; }
        public string CAS_DESC { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
