//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP2_RSM_SECONDARY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSP2_RSM_SECONDARY_TYPE()
        {
            this.DSP2_RSM_MATERIAL_MASTER = new HashSet<DSP2_RSM_MATERIAL_MASTER>();
        }
    
        public decimal SECONDARY_TYPE_SEQNO { get; set; }
        public string SECONDARY_CODE { get; set; }
        public string SECONDARY_NAME { get; set; }
        public decimal MASTER_TYPE_SEQNO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual DSP2_RSM_MASTER_TYPE DSP2_RSM_MASTER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSP2_RSM_MATERIAL_MASTER> DSP2_RSM_MATERIAL_MASTER { get; set; }
    }
}
