//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_SCH_MAIN
    {
        public int MAIN_ID { get; set; }
        public string SYS_ID { get; set; }
        public string PROG_ID { get; set; }
        public string PROG_DESC { get; set; }
        public string PROG_URL { get; set; }
        public string PROG_FREQ { get; set; }
        public string FREQ_DESC { get; set; }
        public string CONTACT_NM { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_MAIL { get; set; }
        public bool IS_MAIL { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
