//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_WORD_MNG
    {
        public int WM_ID { get; set; }
        public string WM_WORD { get; set; }
        public string WM_RELATED1 { get; set; }
        public string WM_RELATED2 { get; set; }
        public string WM_RELATED3 { get; set; }
        public string WM_RELATED4 { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
