//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_TRAAREA
    {
        public int TRAAREA_ID { get; set; }
        public Nullable<int> TRAINFO_ID { get; set; }
        public string AREADESC { get; set; }
        public string CIRCLE1 { get; set; }
        public string CIRCLE2 { get; set; }
        public string CIRCLE3 { get; set; }
        public string CIRCLE4 { get; set; }
        public string CIRCLE5 { get; set; }
        public string CIRCLE6 { get; set; }
        public string CIRCLE7 { get; set; }
        public string CIRCLE8 { get; set; }
        public string CIRCLE9 { get; set; }
        public string CIRCLE10 { get; set; }
        public string CIRCLE11 { get; set; }
        public string CIRCLE12 { get; set; }
        public string CIRCLE13 { get; set; }
        public string CIRCLE14 { get; set; }
        public string CIRCLE15 { get; set; }
        public string CIRCLE16 { get; set; }
        public string CIRCLE17 { get; set; }
        public string CIRCLE18 { get; set; }
        public string CIRCLE19 { get; set; }
        public string CIRCLE20 { get; set; }
        public string CIRCLE21 { get; set; }
        public string CIRCLE22 { get; set; }
        public string CIRCLE23 { get; set; }
        public string CIRCLE24 { get; set; }
        public string CIRCLE25 { get; set; }
        public string CIRCLE26 { get; set; }
        public string CIRCLE27 { get; set; }
        public string CIRCLE28 { get; set; }
        public string CIRCLE29 { get; set; }
        public string CIRCLE30 { get; set; }
        public string CIRCLE31 { get; set; }
        public string CIRCLE32 { get; set; }
        public string CIRCLE33 { get; set; }
        public string CIRCLE34 { get; set; }
        public string CIRCLE35 { get; set; }
        public string CIRCLE36 { get; set; }
        public string CIRCLE37 { get; set; }
        public string CIRCLE38 { get; set; }
        public string CIRCLE39 { get; set; }
        public string CIRCLE40 { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
