//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_TYPHOONDESC
    {
        public int TYPHOONDESC_ID { get; set; }
        public int TYPHOONINFO_ID { get; set; }
        public string T_NO { get; set; }
        public string TYCASE { get; set; }
        public string WARNNO { get; set; }
        public string TENAME { get; set; }
        public string TCNAME { get; set; }
        public string ANALTIME { get; set; }
        public string ANALPOSITION { get; set; }
        public string ANALMAXWINDS { get; set; }
        public string ANALGUST { get; set; }
        public string ANALPRESSURE { get; set; }
        public string ANALRADIUS15 { get; set; }
        public string ANALSCALETW { get; set; }
        public string ANALSCALEEN { get; set; }
        public string PREDTIME { get; set; }
        public string PREDPOSITION { get; set; }
        public string PREDMAXWINDS { get; set; }
        public string PREDGUST { get; set; }
        public string PREDPRESSURE { get; set; }
        public string PREDRADIUS15 { get; set; }
        public string TNOW { get; set; }
        public string TCUR { get; set; }
        public string TWARNAREA { get; set; }
        public string TRAINRPT { get; set; }
        public string TNOTE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
