//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_WS_LOG
    {
        public int LW_ID { get; set; }
        public int LW_WGID { get; set; }
        public int LW_WCID { get; set; }
        public string LW_WGNAME { get; set; }
        public bool LW_WGAUTH { get; set; }
        public bool LW_WGSTATE { get; set; }
        public string LW_WCCONTACT { get; set; }
        public string LW_WGORG { get; set; }
        public string LW_WCSYSNAME { get; set; }
        public string LW_WCIP { get; set; }
        public string LW_FROMIP { get; set; }
        public short LW_ERRCODE { get; set; }
        public string LW_ERRDESC { get; set; }
        public System.DateTime LW_DATETIME { get; set; }
        public string LW_INP { get; set; }
        public string LW_OUP { get; set; }
    }
}
