//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_DM_DATA
    {
        public int DATA_ID { get; set; }
        public int CABINET_ID { get; set; }
        public string FLD01 { get; set; }
        public string FLD02 { get; set; }
        public string FLD03 { get; set; }
        public string FLD04 { get; set; }
        public string FLD05 { get; set; }
        public string FLD06 { get; set; }
        public string FLD07 { get; set; }
        public string FLD08 { get; set; }
        public string FLD09 { get; set; }
        public string FLD10 { get; set; }
        public string FLD11 { get; set; }
        public string FLD12 { get; set; }
        public string FLD13 { get; set; }
        public string FLD14 { get; set; }
        public string FLD15 { get; set; }
        public string FLD16 { get; set; }
        public string FLD17 { get; set; }
        public string FLD18 { get; set; }
        public string FLD19 { get; set; }
        public string FLD20 { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
