//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_MTMP_XLS_RESOURCE_STOCK_DATA
    {
        public int MTMP_DETAIL_ID { get; set; }
        public int MTMP_REC_ID { get; set; }
        public Nullable<int> UNIT_LOCATION_ID { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public string UNIT_NAME { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public string CURRENT_QTY { get; set; }
        public string AVAILABLE_QTY { get; set; }
        public Nullable<short> DATA_ERROR { get; set; }
        public string ERROR_REASON { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
