//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_SECONDARY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDD2_SECONDARY_TYPE()
        {
            this.EDD2_DETAIL_TYPE = new HashSet<EDD2_DETAIL_TYPE>();
        }
    
        public int SECONDARY_TYPE_ID { get; set; }
        public int MASTER_TYPE_ID { get; set; }
        public string SECONDARY_TYPE_NAME { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDD2_DETAIL_TYPE> EDD2_DETAIL_TYPE { get; set; }
        public virtual EDD2_MASTER_TYPE EDD2_MASTER_TYPE { get; set; }
    }
}
