//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_RESOURCE_ITEM
    {
        public int RESOURCE_ID { get; set; }
        public int DETAIL_TYPE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<int> SIZE_UOM { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<int> WEIGHT_UOM { get; set; }
        public Nullable<decimal> ENERGY_VOLUMN { get; set; }
        public Nullable<int> ENERGY_UOM { get; set; }
        public Nullable<decimal> EFFICACY { get; set; }
        public Nullable<int> EFFICACY_UOM { get; set; }
        public Nullable<short> BEARING_NO { get; set; }
        public Nullable<short> OPERATOR_NO { get; set; }
        public string RESOURCE_SPEC { get; set; }
        public int STANDARD_UOM { get; set; }
        public string RETURN_CODE { get; set; }
        public string SHARE_FLAG { get; set; }
        public string FIREFIGHTING_RESOURCE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EDD2_DETAIL_TYPE EDD2_DETAIL_TYPE { get; set; }
    }
}
