//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_RESPONSE_EOC
    {
        public int REQUEST_DETAIL_ID { get; set; }
        public string EOC_ID { get; set; }
        public Nullable<System.DateTime> SUPPORT_TIME { get; set; }
        public Nullable<System.DateTime> RESPONSE_TIME { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<int> PLAN_QTY { get; set; }
        public string LEATHER_INFO { get; set; }
        public string LEATHER_TEL { get; set; }
        public string LEATHER_MOBILE { get; set; }
        public string LEATHER_TEL2 { get; set; }
        public string LEATHER_MEMO { get; set; }
        public int RESPONSE_EOC_ID { get; set; }
    }
}
