//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_RESOURCE_REQUEST
    {
        public string APPLY_EOC { get; set; }
        public System.DateTime REQUEST_TIME { get; set; }
        public string APPLY_UNIT_NAME { get; set; }
        public string APPLY_NAME { get; set; }
        public string APPLY_TITLE { get; set; }
        public string APPLY_CONTACT_TEL { get; set; }
        public string APPLY_CONTACT_EXT { get; set; }
        public string APPLY_MOBILE { get; set; }
        public string REQUEST_UNIT { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_EXT { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string ADDR_FULL { get; set; }
        public string TWD97_X { get; set; }
        public string TWD97_Y { get; set; }
        public string WGS84_X { get; set; }
        public string WGS84_Y { get; set; }
        public string SUPPORT_EOC { get; set; }
        public string DISASTER_NAME { get; set; }
        public string SUPPORT_CITY_ID { get; set; }
        public string SUPPORT_TOWN_ID { get; set; }
        public string REQUEST_REMARK { get; set; }
        public Nullable<System.DateTime> RELEASE_TIME { get; set; }
        public string RELEASE_USER { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string REQUEST_STATUS { get; set; }
        public string RESPONSE_UNIT { get; set; }
        public string REFERRED_STATE { get; set; }
        public Nullable<System.DateTime> REFERRED_TIME { get; set; }
        public string REFERRED_EOC { get; set; }
        public Nullable<long> PRJ_NO { get; set; }
        public int RESOURCE_REQUEST_ID { get; set; }
        public string MEMO_N { get; set; }
        public string STATUS_MEMO_S { get; set; }
    }
}
