//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EVENT_PHONE
    {
        public decimal PHONE_UID { get; set; }
        public decimal LIST_UID { get; set; }
        public Nullable<System.DateTime> PHON_TIME { get; set; }
        public string PHON_TEST_NAME { get; set; }
        public string PHON_MEM_NAME { get; set; }
        public string PHON_CONT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EEM2_EVENT_LIST EEM2_EVENT_LIST { get; set; }
    }
}
