//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_SIGNIN
    {
        public decimal SUID { get; set; }
        public string S_FORM_NAME { get; set; }
        public string STYPE { get; set; }
        public string CITY_NAME { get; set; }
        public string EOC_ID { get; set; }
        public Nullable<decimal> PRJ_NO { get; set; }
        public string LOGIN_ACCOUNT { get; set; }
        public string S_NAME { get; set; }
        public Nullable<decimal> ORG_ID { get; set; }
        public string S_UNIT { get; set; }
        public Nullable<System.DateTime> SIGN_IN_TIME { get; set; }
        public Nullable<System.DateTime> SIGN_OUT_TIME { get; set; }
        public string TEL { get; set; }
        public string MEMO_S { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> EOC_ID_OLD { get; set; }
    
        public virtual EEM2_SIGNIN EEM2_SIGNIN1 { get; set; }
        public virtual EEM2_SIGNIN EEM2_SIGNIN2 { get; set; }
    }
}
