//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_NEWS_MERGE_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_NEWS_MERGE_MAIN()
        {
            this.EEM2_NEWS_MERGE_REC = new HashSet<EEM2_NEWS_MERGE_REC>();
        }
    
        public decimal MERGE_SUID { get; set; }
        public decimal PRJ_NO { get; set; }
        public Nullable<System.DateTime> CASE_MERGE_TIME { get; set; }
        public string CASE_MERGE_PERSON { get; set; }
        public decimal NEWS_UID { get; set; }
        public string MERGE_HISTORY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_NEWS_MERGE_REC> EEM2_NEWS_MERGE_REC { get; set; }
    }
}
