//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_ORG_INFO
    {
        public string EOC_ID { get; set; }
        public decimal ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string ADDR_FULL { get; set; }
        public Nullable<decimal> TWD97_X { get; set; }
        public Nullable<decimal> TWD97_Y { get; set; }
        public Nullable<decimal> WGS_X { get; set; }
        public Nullable<decimal> WGS_Y { get; set; }
        public Nullable<int> SHOW_ORDER { get; set; }
        public string IS_ON_OFF { get; set; }
        public string ORG_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> ORG_ID_OLD { get; set; }
    
        public virtual EEM2_EOC_DATA EEM2_EOC_DATA { get; set; }
        public virtual EEM2_EOC_DATA EEM2_EOC_DATA1 { get; set; }
        public virtual EEM2_EOC_DATA EEM2_EOC_DATA2 { get; set; }
        public virtual EEM2_EOC_DATA EEM2_EOC_DATA3 { get; set; }
    }
}
