//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EOC_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_EOC_DATA()
        {
            this.EEM2_ORG_INFO = new HashSet<EEM2_ORG_INFO>();
            this.EEM2_ORG_INFO1 = new HashSet<EEM2_ORG_INFO>();
            this.EEM2_ORG_INFO2 = new HashSet<EEM2_ORG_INFO>();
            this.EEM2_ORG_INFO3 = new HashSet<EEM2_ORG_INFO>();
            this.EEM2_RELEASE_TEMPLATE = new HashSet<EEM2_RELEASE_TEMPLATE>();
            this.EEM2_RELEASE_TEMPLATE1 = new HashSet<EEM2_RELEASE_TEMPLATE>();
            this.EEM2_EOC_PRJ = new HashSet<EEM2_EOC_PRJ>();
        }
    
        public string EOC_ID { get; set; }
        public string DEP_CODE { get; set; }
        public string DEP_NAME { get; set; }
        public string EOC_NAME { get; set; }
        public string EOC_PARENT { get; set; }
        public string IS_ON_OFF { get; set; }
        public string MEMO_S { get; set; }
        public string EOC_LEVEL { get; set; }
        public string CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
        public int SHOW_ORDER { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public decimal EOC_ID_OLD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_ORG_INFO> EEM2_ORG_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_ORG_INFO> EEM2_ORG_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_ORG_INFO> EEM2_ORG_INFO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_ORG_INFO> EEM2_ORG_INFO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_RELEASE_TEMPLATE> EEM2_RELEASE_TEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_RELEASE_TEMPLATE> EEM2_RELEASE_TEMPLATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EOC_PRJ> EEM2_EOC_PRJ { get; set; }
    }
}
