//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_COORD_REPORT
    {
        public decimal COORD_UID { get; set; }
        public decimal PRJ_NO { get; set; }
        public System.DateTime REPORT_TIME { get; set; }
        public string CITY_NAME { get; set; }
        public string COORDINATOR1 { get; set; }
        public string COORDINATOR2 { get; set; }
        public string IS_CLOSE { get; set; }
        public int REPORT_INDEX { get; set; }
        public string STATUS { get; set; }
        public System.DateTime EOC_INFO_OPEN_TIME { get; set; }
        public Nullable<decimal> EOC_PRJ_NO { get; set; }
        public string EOC_INFO_COMMANDER { get; set; }
        public string EOC_INFO_ORG { get; set; }
        public Nullable<int> WORK_COUNT { get; set; }
        public string WORK_HOST { get; set; }
        public string WORK_RESOLUTION { get; set; }
        public string WORK_FILE_NAME { get; set; }
        public string WORK_FILE_ID { get; set; }
        public string WORK_FILE_REMARK { get; set; }
        public string DISASTER { get; set; }
        public string DISASTER_FILE_NAME { get; set; }
        public string DISASTER_FILE_ID { get; set; }
        public string DISASTER_FILE_REMARK { get; set; }
        public string REFUGE_INFO { get; set; }
        public string REFUGE_FILE_NAME { get; set; }
        public string REFUGE_FILE_ID { get; set; }
        public string REFUGE_FILE_REMARK { get; set; }
        public string OTHER_DISASTER { get; set; }
        public string SUPPORT { get; set; }
        public string OTHER_SITUATION { get; set; }
        public string WEATHER_CONDITION { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
