//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_RPT_B1
    {
        public int RPT_DETAIL_ID { get; set; }
        public int RPT_MAIN_ID { get; set; }
        public string CITY_NAME { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> DUMP_LOST { get; set; }
        public Nullable<int> PLANT_LOST { get; set; }
        public Nullable<int> STATION_LOST { get; set; }
        public Nullable<int> BUILDING_LOST { get; set; }
        public Nullable<int> DUMP_RECOVERY { get; set; }
        public Nullable<int> PLANT_RECOVERY { get; set; }
        public Nullable<int> STATION_RECOVERY { get; set; }
        public Nullable<int> BUILDING_RECOVERY { get; set; }
        public string SHOW_ORDER { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
