//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_EVACUATE
    {
        public int SEQ_ID { get; set; }
        public int DISP_DETAIL_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string VILLAGE_NAME { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string PLACE { get; set; }
        public string ACCEPT_PLACE { get; set; }
        public Nullable<int> ESTIMATE_PNUM { get; set; }
        public Nullable<int> RETREAT_PNUM { get; set; }
        public Nullable<int> SUM_PNUM { get; set; }
        public string SHOW_ORDER { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual ERA2_DISP_DETAIL ERA2_DISP_DETAIL { get; set; }
    }
}
