//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_RPT_A3a
    {
        public int RPT_DETAIL_ID { get; set; }
        public int RPT_MAIN_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public Nullable<int> TRAPPED { get; set; }
        public Nullable<int> RESCUES { get; set; }
        public Nullable<int> WATER_SUPPLIES { get; set; }
        public Nullable<int> FIRE_STAFF { get; set; }
        public Nullable<int> FIRE_VEHICLES { get; set; }
        public Nullable<int> FIRE_BOAT { get; set; }
        public Nullable<int> FIRE_HELICOPTERS { get; set; }
        public Nullable<int> FIRE_VOL_STAFF { get; set; }
        public Nullable<int> FIRE_VOL_VEHICLES { get; set; }
        public Nullable<int> FIRE_VOL_BOAT { get; set; }
        public Nullable<int> FOLK_STAFF { get; set; }
        public Nullable<int> FOLK_VEHICLES { get; set; }
        public Nullable<int> FOLK_BOAT { get; set; }
        public Nullable<int> SEARCH_STAFF { get; set; }
        public Nullable<int> SEARCH_VEHICLES { get; set; }
        public Nullable<int> SEARCH_BOAT { get; set; }
        public Nullable<int> POLICE_STAFF { get; set; }
        public Nullable<int> POLICE_VEHICLES { get; set; }
        public Nullable<int> POLICE_BOAT { get; set; }
        public Nullable<int> POLICE_VOL_STAFF { get; set; }
        public Nullable<int> POLICE_VOL_VEHICLES { get; set; }
        public Nullable<int> MILITARY_VOL_STAFF { get; set; }
        public Nullable<int> MILITARY_VOL_VEHICLES { get; set; }
        public Nullable<int> MILITARY_STAFF { get; set; }
        public Nullable<int> MILITARY_VEHICLES { get; set; }
        public Nullable<int> MILITARY_BOAT { get; set; }
        public Nullable<int> MILITARY_HELICOPTERS { get; set; }
        public Nullable<int> OTHERS { get; set; }
        public string SHOW_ORDER { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
