//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_DISPATCH_HELICOPTER
    {
        public int SEQ_ID { get; set; }
        public int DISP_DETAIL_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public Nullable<int> COUNTRYARMY { get; set; }
        public Nullable<int> AIRDUTY { get; set; }
        public Nullable<int> COUNTRYARMY1 { get; set; }
        public Nullable<int> AIRDUTY1 { get; set; }
        public Nullable<int> COUNTRYARMY2 { get; set; }
        public Nullable<int> AIRDUTY2 { get; set; }
        public Nullable<int> COUNTRYARMY3 { get; set; }
        public Nullable<int> AIRDUTY3 { get; set; }
        public Nullable<int> COUNTRYARMY4 { get; set; }
        public Nullable<int> AIRDUTY4 { get; set; }
        public Nullable<int> COUNTRYARMY5 { get; set; }
        public Nullable<int> AIRDUTY5 { get; set; }
        public Nullable<int> COUNTRYARMY6 { get; set; }
        public Nullable<int> AIRDUTY6 { get; set; }
        public Nullable<int> COUNTRYARMY7 { get; set; }
        public Nullable<int> AIRDUTY7 { get; set; }
        public string SHOW_ORDER { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual ERA2_DISP_DETAIL ERA2_DISP_DETAIL { get; set; }
    }
}
