//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_MOUNTAIN_CONTACT
    {
        public int SEQ_ID { get; set; }
        public int DISP_DETAIL_ID { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public Nullable<int> APPLY_IN_SET { get; set; }
        public Nullable<int> APPLY_IN_NUM { get; set; }
        public Nullable<int> DISSUADE_SET { get; set; }
        public Nullable<int> DISSUADE_NUM { get; set; }
        public Nullable<int> OUT_SET { get; set; }
        public Nullable<int> OUT_NUM { get; set; }
        public Nullable<int> SAFE_SET { get; set; }
        public Nullable<int> SAFE_NUM { get; set; }
        public Nullable<int> REFUGE_SET { get; set; }
        public Nullable<int> REFUGE_NUM { get; set; }
        public Nullable<int> DOWN_SET { get; set; }
        public Nullable<int> DOWN_NUM { get; set; }
        public Nullable<int> CONT_N_SET { get; set; }
        public Nullable<int> CONT_N_NUM { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual ERA2_DISP_DETAIL ERA2_DISP_DETAIL { get; set; }
    }
}
