//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_ATMP_A2a
    {
        public int ATMP_DETAIL_ID { get; set; }
        public int ATMP_REC_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public Nullable<int> LOW_LEVEL { get; set; }
        public Nullable<int> MOUNTAIN { get; set; }
        public Nullable<int> SEASIDE { get; set; }
        public Nullable<int> RIVERS { get; set; }
        public Nullable<int> BUILDS { get; set; }
        public Nullable<int> OTHERS { get; set; }
        public Nullable<int> SUGGESTS_ALL { get; set; }
        public Nullable<int> SUGGESTS_NPA { get; set; }
        public Nullable<int> SUGGESTS_NFA { get; set; }
        public Nullable<int> SUGGESTS_CGA { get; set; }
        public Nullable<int> SUGGESTS_GOV { get; set; }
        public Nullable<int> SUGGESTS_OTR { get; set; }
        public Nullable<int> EXECUTES_ALL { get; set; }
        public Nullable<int> EXECUTES_NPA { get; set; }
        public Nullable<int> EXECUTES_NFA { get; set; }
        public Nullable<int> EXECUTES_CGA { get; set; }
        public Nullable<int> EXECUTES_GOV { get; set; }
        public Nullable<int> EXECUTES_OTR { get; set; }
        public Nullable<int> RELIEVES { get; set; }
        public string MEMO { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
