//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERA2_DISP_DETAIL()
        {
            this.ERA2_DISP_AIR_CANCEL = new HashSet<ERA2_DISP_AIR_CANCEL>();
            this.ERA2_DISP_ALERT_AREAS = new HashSet<ERA2_DISP_ALERT_AREAS>();
            this.ERA2_DISP_BRIDGE_CLOSED = new HashSet<ERA2_DISP_BRIDGE_CLOSED>();
            this.ERA2_DISP_CASUALTIES = new HashSet<ERA2_DISP_CASUALTIES>();
            this.ERA2_DISP_CONTENT = new HashSet<ERA2_DISP_CONTENT>();
            this.ERA2_DISP_DISPATCH_HELICOPTER = new HashSet<ERA2_DISP_DISPATCH_HELICOPTER>();
            this.ERA2_DISP_EARTHQUAKE = new HashSet<ERA2_DISP_EARTHQUAKE>();
            this.ERA2_DISP_EVACUATE = new HashSet<ERA2_DISP_EVACUATE>();
            this.ERA2_DISP_FISHERMEN_PLACE = new HashSet<ERA2_DISP_FISHERMEN_PLACE>();
            this.ERA2_DISP_HIGHRISK_AREAS = new HashSet<ERA2_DISP_HIGHRISK_AREAS>();
            this.ERA2_DISP_INDUSTRY_LOSE = new HashSet<ERA2_DISP_INDUSTRY_LOSE>();
            this.ERA2_DISP_INTENSITY = new HashSet<ERA2_DISP_INTENSITY>();
            this.ERA2_DISP_LANDSLIDE_ALERT = new HashSet<ERA2_DISP_LANDSLIDE_ALERT>();
            this.ERA2_DISP_LIFELINES_DAMAGES = new HashSet<ERA2_DISP_LIFELINES_DAMAGES>();
            this.ERA2_DISP_LOCAL_FLOOD = new HashSet<ERA2_DISP_LOCAL_FLOOD>();
            this.ERA2_DISP_MANPOWER = new HashSet<ERA2_DISP_MANPOWER>();
            this.ERA2_DISP_MOUNTAIN_CONTACT = new HashSet<ERA2_DISP_MOUNTAIN_CONTACT>();
            this.ERA2_DISP_PEOPLE_CAMP = new HashSet<ERA2_DISP_PEOPLE_CAMP>();
            this.ERA2_DISP_PEOPLE_MISSING = new HashSet<ERA2_DISP_PEOPLE_MISSING>();
            this.ERA2_DISP_RAILROAD_CANCEL = new HashSet<ERA2_DISP_RAILROAD_CANCEL>();
            this.ERA2_DISP_RAINFALL = new HashSet<ERA2_DISP_RAINFALL>();
            this.ERA2_DISP_REFUGE = new HashSet<ERA2_DISP_REFUGE>();
            this.ERA2_DISP_RESPONSE_TEAM = new HashSet<ERA2_DISP_RESPONSE_TEAM>();
            this.ERA2_DISP_ROADS_BLOCKED = new HashSet<ERA2_DISP_ROADS_BLOCKED>();
            this.ERA2_DISP_STATE_SITUATION = new HashSet<ERA2_DISP_STATE_SITUATION>();
            this.ERA2_DISP_SUPPORT_CITY = new HashSet<ERA2_DISP_SUPPORT_CITY>();
            this.ERA2_DISP_TRAFFIC_BLOCK = new HashSet<ERA2_DISP_TRAFFIC_BLOCK>();
            this.ERA2_DISP_TSUNAMI = new HashSet<ERA2_DISP_TSUNAMI>();
            this.ERA2_DISP_WATER_RESOURCE = new HashSet<ERA2_DISP_WATER_RESOURCE>();
            this.ERA2_DISP_WIND = new HashSet<ERA2_DISP_WIND>();
        }
    
        public int DISP_DETAIL_ID { get; set; }
        public int DISP_MAIN_ID { get; set; }
        public int DISP_STYLE_ID { get; set; }
        public Nullable<System.DateTime> COUNT_SDATE { get; set; }
        public Nullable<System.DateTime> COUNT_EDATE { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_AIR_CANCEL> ERA2_DISP_AIR_CANCEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_ALERT_AREAS> ERA2_DISP_ALERT_AREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_BRIDGE_CLOSED> ERA2_DISP_BRIDGE_CLOSED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_CASUALTIES> ERA2_DISP_CASUALTIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_CONTENT> ERA2_DISP_CONTENT { get; set; }
        public virtual ERA2_DISP_MAIN ERA2_DISP_MAIN { get; set; }
        public virtual ERA2_DISP_STYLE ERA2_DISP_STYLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_DISPATCH_HELICOPTER> ERA2_DISP_DISPATCH_HELICOPTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_EARTHQUAKE> ERA2_DISP_EARTHQUAKE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_EVACUATE> ERA2_DISP_EVACUATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_FISHERMEN_PLACE> ERA2_DISP_FISHERMEN_PLACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_HIGHRISK_AREAS> ERA2_DISP_HIGHRISK_AREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_INDUSTRY_LOSE> ERA2_DISP_INDUSTRY_LOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_INTENSITY> ERA2_DISP_INTENSITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_LANDSLIDE_ALERT> ERA2_DISP_LANDSLIDE_ALERT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_LIFELINES_DAMAGES> ERA2_DISP_LIFELINES_DAMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_LOCAL_FLOOD> ERA2_DISP_LOCAL_FLOOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_MANPOWER> ERA2_DISP_MANPOWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_MOUNTAIN_CONTACT> ERA2_DISP_MOUNTAIN_CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_PEOPLE_CAMP> ERA2_DISP_PEOPLE_CAMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_PEOPLE_MISSING> ERA2_DISP_PEOPLE_MISSING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_RAILROAD_CANCEL> ERA2_DISP_RAILROAD_CANCEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_RAINFALL> ERA2_DISP_RAINFALL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_REFUGE> ERA2_DISP_REFUGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_RESPONSE_TEAM> ERA2_DISP_RESPONSE_TEAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_ROADS_BLOCKED> ERA2_DISP_ROADS_BLOCKED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_STATE_SITUATION> ERA2_DISP_STATE_SITUATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_SUPPORT_CITY> ERA2_DISP_SUPPORT_CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_TRAFFIC_BLOCK> ERA2_DISP_TRAFFIC_BLOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_TSUNAMI> ERA2_DISP_TSUNAMI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_WATER_RESOURCE> ERA2_DISP_WATER_RESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_WIND> ERA2_DISP_WIND { get; set; }
    }
}
