//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_STYLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERA2_DISP_STYLE()
        {
            this.ERA2_DISP_DETAIL = new HashSet<ERA2_DISP_DETAIL>();
        }
    
        public int DISP_STYLE_ID { get; set; }
        public string DISP_CAT_ID { get; set; }
        public string DISP_CAT_NAME { get; set; }
        public short ITEM_LEVEL { get; set; }
        public string ITEM_ORDER { get; set; }
        public string ITEM_TITLE { get; set; }
        public string ITEM_FROM { get; set; }
        public string ITEM_TYPE { get; set; }
        public short ORG_LEVEL_ID { get; set; }
        public string PRG_ID { get; set; }
        public string DISP_ENABLE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERA2_DISP_DETAIL> ERA2_DISP_DETAIL { get; set; }
    }
}
