//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_DISP_LOCAL_FLOOD
    {
        public int SEQ_ID { get; set; }
        public int DISP_DETAIL_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string PLACE { get; set; }
        public Nullable<System.DateTime> START_FLOOD { get; set; }
        public Nullable<System.DateTime> END_FLOOD { get; set; }
        public Nullable<decimal> FLOOD_DEPTH { get; set; }
        public Nullable<decimal> FLOOD_AREA { get; set; }
        public Nullable<int> FLOOD_HOUSE { get; set; }
        public string REMARK { get; set; }
        public string SHOW_ORDER { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual ERA2_DISP_DETAIL ERA2_DISP_DETAIL { get; set; }
    }
}
