//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS2_ACTION_LOG
    {
        public decimal ACTION_SEQNO { get; set; }
        public string LOGIN_SEQNO { get; set; }
        public decimal PERSON_UID { get; set; }
        public string FUNC_ID { get; set; }
        public int PEOPLEMISSING_RESUAL_CNT { get; set; }
        public int SHELTERS_RESUAL_CNT { get; set; }
        public int EVACUATEREPORT_RESUAL_CNT { get; set; }
        public int STAYHERE_RESUAL_CNT { get; set; }
        public int IMP_RESUAL_CNT { get; set; }
        public int EMS_RESUAL_CNT { get; set; }
        public int PEOPLEMISSING_FOUND_CNT { get; set; }
        public int SHELTERS_FOUND_CNT { get; set; }
        public int EVACUATEREPORT_FOUND_CNT { get; set; }
        public int STAYHERE_FOUND_CNT { get; set; }
        public int IMP_FOUND_CNT { get; set; }
        public int EMS_FOUND_CNT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
