//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS2_EMS_PATIENT
    {
        public decimal SEQNO { get; set; }
        public string EMS_DID { get; set; }
        public string PATIENT { get; set; }
        public string HOSPITAL { get; set; }
        public Nullable<int> AGE { get; set; }
        public string AREA { get; set; }
        public string SEX { get; set; }
        public string NATION { get; set; }
        public string CASENO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
