//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS2_SEARCH_MAIN
    {
        public decimal SEQNO_M { get; set; }
        public string FIND_SOURCE { get; set; }
        public string PERSON_NAME { get; set; }
        public string PERSON_SEX { get; set; }
        public string PERSON_IDNO { get; set; }
        public Nullable<decimal> BIRTHDAY_YEAR { get; set; }
        public Nullable<int> PERSON_AGE { get; set; }
        public string PERSON_PHONE { get; set; }
        public string CITIZENSHIP { get; set; }
        public string LOCATION_DESC { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string VILLAGE_NAME { get; set; }
        public string ADDR { get; set; }
        public string WGS84_X { get; set; }
        public string WGS84_Y { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_ID { get; set; }
        public string PERSON_INFO { get; set; }
        public string USE_MEMO { get; set; }
        public Nullable<System.DateTime> VALID_DATE { get; set; }
        public string OFFER_NAME { get; set; }
        public string OFFER_TEL { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
