//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS2_LOOKFOR
    {
        public decimal LOOKFOR_SEQNO { get; set; }
        public decimal PERSON_UID { get; set; }
        public string LOOKFOR_PERSON_NAME { get; set; }
        public string PERSON_SEX { get; set; }
        public Nullable<decimal> BIRTHDAY_YEAR { get; set; }
        public Nullable<int> PERSON_AGE { get; set; }
        public string CITIZENSHIP { get; set; }
        public string CITY_NAME { get; set; }
        public string LOGIN_PERSON_EMAIL { get; set; }
        public string LOOKFOR_STATUS { get; set; }
        public decimal SUCCESS_REC_NO { get; set; }
        public string DISP_FLAG { get; set; }
        public Nullable<decimal> STARTUP_SEQNO { get; set; }
        public string LOOKFOR_COUNTY { get; set; }
        public string LOOKFOR_TOWN { get; set; }
        public string LOOKFOR_SYS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
