//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTS_FU_TEMPL
    {
        public int FT_ID { get; set; }
        public string FT_NAME { get; set; }
        public int FT_RANGE { get; set; }
        public string FT_TITLE { get; set; }
        public string FT_KEYWORD { get; set; }
        public string FT_AUTHOR { get; set; }
        public string FT_DESC { get; set; }
        public string FT_CREATED_TIME { get; set; }
        public string FT_DATA_TYPE { get; set; }
        public string FT_SOURCE { get; set; }
        public string FT_AUTHORITY { get; set; }
    }
}
