//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTS_FU_FILES
    {
        public int FF_ID { get; set; }
        public Nullable<int> FM_ID { get; set; }
        public string FF_NAME { get; set; }
        public string FF_FORMAT { get; set; }
        public Nullable<int> FF_SIZE { get; set; }
        public string FF_MD5 { get; set; }
        public Nullable<int> FF_VERSION { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string WD_ID { get; set; }
        public string WD_ID2 { get; set; }
        public string WD_ID3 { get; set; }
    }
}
