//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDS2_BASIS
    {
        public int MAIN_ID { get; set; }
        public string EOC_ID { get; set; }
        public long PRJ_NO { get; set; }
        public string PRJ_NAME { get; set; }
        public string PRJ_TYPE { get; set; }
        public Nullable<System.DateTime> CASE_STIME { get; set; }
        public Nullable<System.DateTime> CASE_ETIME { get; set; }
        public string CASE_YEAR { get; set; }
        public string TY_INVASION_PATH { get; set; }
        public string TY_INTENSITY { get; set; }
        public string TY_EFFECT { get; set; }
        public string TY_COUNTY_ID_ARRAY { get; set; }
        public Nullable<decimal> FLOOD_RAINFALL_HOURS { get; set; }
        public string FLOOD_CAUSE { get; set; }
        public string QUAKE_NAME { get; set; }
        public Nullable<System.DateTime> QUAKE_TIME { get; set; }
        public string QUAKE_CAUSE { get; set; }
        public string QUAKE_COUNTY_ID { get; set; }
        public string QUAKE_EPICENTER { get; set; }
        public Nullable<decimal> QUAKE_DEPTH { get; set; }
        public string OBSERVATION_ELSE { get; set; }
        public string TY_MAKE_LANDFALL { get; set; }
        public Nullable<decimal> TY_RAINFALL { get; set; }
        public Nullable<decimal> TY_WARNING_HOURS { get; set; }
        public Nullable<decimal> TY_EMIC_DAYS { get; set; }
        public string TY_RAINFALL_TOP1 { get; set; }
        public string TY_RAINFALL_TOP2 { get; set; }
        public string TY_RAINFALL_TOP3 { get; set; }
        public string TY_RAINFALL_TOP4 { get; set; }
        public string TY_RAINFALL_TOP5 { get; set; }
        public Nullable<decimal> FLOOD_RAINFALL { get; set; }
        public Nullable<decimal> FLOOD_HOURS { get; set; }
        public Nullable<decimal> QUAKE_SCALE { get; set; }
        public Nullable<decimal> QUAKE_MAGNITUDE { get; set; }
        public string QUAKE_COUNTY_ID_ARRAY { get; set; }
        public string BROKEN_RECORD { get; set; }
        public string MEMO { get; set; }
        public string SCALE_ELSE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string WGS84_Y { get; set; }
        public string WGS84_X { get; set; }
    }
}
