//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTT2_BULLETIN_11
    {
        public long BULLETIN_MAIN_ID { get; set; }
        public string RECEIVE_EOC { get; set; }
        public long PRJ_NO { get; set; }
        public string QUALIFIED { get; set; }
        public string TRANSFER_EOC { get; set; }
        public System.DateTime TRANSFER_TIME { get; set; }
        public string EOC_OPEN_TIER { get; set; }
        public string REESPONSE_FILE { get; set; }
        public string FAX_ARRIVE_NO { get; set; }
        public Nullable<System.DateTime> FAX_ARRIVE_TIME { get; set; }
        public string RE_TRANSFER_NO { get; set; }
        public Nullable<System.DateTime> RE_TRANSFER_TIME { get; set; }
        public string RESPONSE_CODE { get; set; }
        public int RESPONSE_LIMIT { get; set; }
        public string SIGN_LEVEL { get; set; }
        public string EMAIL_CODE { get; set; }
        public string SMS_CODE { get; set; }
        public string RECEIVE_USER { get; set; }
        public Nullable<System.DateTime> RECEIVE_TIME { get; set; }
        public string RESPONSE_FAX { get; set; }
        public string RESPONSE_USER { get; set; }
        public Nullable<System.DateTime> RESPONSE_TIME { get; set; }
        public string RE_RESPONSE_FAX { get; set; }
        public string RE_RESPONSE_USER { get; set; }
        public Nullable<System.DateTime> RE_RESPONSE_TIME { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<int> RESPONSE_COUNT { get; set; }
        public string SIGN_NAME { get; set; }
        public string SIGN_FILE { get; set; }
        public string MEMO_N { get; set; }
        public long BULLETIN_DETAIL_ID { get; set; }
    }
}
