//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSO2_USER_INFO
    {
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public string MAIL { get; set; }
        public string ADDR_FULL { get; set; }
        public string TELC { get; set; }
        public string TELH { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string COMPANY { get; set; }
        public string COMPANY_CODE { get; set; }
        public string USER_OID { get; set; }
        public string PARENT_OID { get; set; }
        public string DEPARTMENT { get; set; }
        public string TITLE { get; set; }
        public string EOC_ID { get; set; }
        public string IDENTITY { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<System.DateTime> PWD_RESET { get; set; }
        public int FAILURE { get; set; }
        public Nullable<System.DateTime> LOCKED_TIME { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string OLDACCOUNT_TYPE { get; set; }
        public string SOURCE_FROM { get; set; }
        public string CREATED_USER { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
