//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSO2_ACCESS_LOG
    {
        public int ID { get; set; }
        public System.DateTime ACCESS_TIME { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string COMPANY { get; set; }
        public string ACCESS { get; set; }
        public string ACCOUNT_TYPE_NAME { get; set; }
    }
}
