//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSO2_USER_TOKEN
    {
        public int TOKEN_ID { get; set; }
        public string USERID { get; set; }
        public string TOKEN { get; set; }
        public string REFRESHTOKEN { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string LOGIN_SYS_CODE { get; set; }
        public System.DateTime EXP_TIME { get; set; }
        public string MOD_SYS_CODE { get; set; }
        public Nullable<System.DateTime> MOD_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_TEL { get; set; }
        public string USER_EMAIL { get; set; }
    }
}
