//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM2_TASK_INFO
    {
        public string EOC_ID { get; set; }
        public string PRJ_NO { get; set; }
        public string TASK_ID { get; set; }
        public System.DateTime TASK_TIME { get; set; }
        public string TASK_DESC { get; set; }
        public string TASK_USER_NAME { get; set; }
        public string TASK_ORG_ID { get; set; }
        public string TASK_LOCATION { get; set; }
        public string TASK_COORDINATE_TYPE { get; set; }
        public string TASK_TWD97_PTS { get; set; }
        public string TASK_WGS84_PTS { get; set; }
        public string TASK_CONDITION { get; set; }
        public string COMBINE_TASK_ID { get; set; }
        public string TASK_STATUS { get; set; }
        public string IS_DEL { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
