//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM2_UPLOAD_FILE
    {
        public string EOC_ID { get; set; }
        public string PRJ_NO { get; set; }
        public string CASE_NO { get; set; }
        public string FILE_ID { get; set; }
        public string FILE_PATH { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_FORMAT { get; set; }
        public string CASE_RENEW_ID { get; set; }
        public string DSP_FILEID { get; set; }
        public string SENT_INFO { get; set; }
    }
}
