//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP2_DI_DEBRISINFO
    {
        public decimal DEBRISINFO_ID { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Vill { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public Nullable<int> AlertValue { get; set; }
        public string AlertLevel { get; set; }
        public string Debrisno { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
