//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP2_RSM_STOCK_DETAIL
    {
        public decimal STOCK_SEQNO { get; set; }
        public string SMALLEST_UNIT { get; set; }
        public Nullable<int> CUTNUM { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public string PACKAGE_SPEC { get; set; }
        public string EXPIRE_DATE { get; set; }
        public decimal STOCK_QTY { get; set; }
        public decimal LOCATION_SEQNO { get; set; }
        public decimal MATERIAL_SEQNO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual DSP2_RSM_LOCATION DSP2_RSM_LOCATION { get; set; }
        public virtual DSP2_RSM_MATERIAL_MASTER DSP2_RSM_MATERIAL_MASTER { get; set; }
    }
}
