//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP2_RSM_LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSP2_RSM_LOCATION()
        {
            this.DSP2_RSM_STOCK_DETAIL = new HashSet<DSP2_RSM_STOCK_DETAIL>();
        }
    
        public decimal LOCATION_SEQNO { get; set; }
        public string LOCATION_NO { get; set; }
        public string LOCATION_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string REGION_NAME { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string IS_USE { get; set; }
        public string MANAGER_LEVEL { get; set; }
        public string MANAGER_UNIT { get; set; }
        public string MANAGER_NAME { get; set; }
        public string MANAGER_TEL { get; set; }
        public string MANAGER_MOBILE { get; set; }
        public string MANAGER_EMAIL { get; set; }
        public string ZIP_CODE { get; set; }
        public string STORE_STATE_NAME { get; set; }
        public string STORE_REGION_NAME { get; set; }
        public string STORE_VILLAGE { get; set; }
        public string STORE_ADDR { get; set; }
        public string LOCATION_LONGITUDE { get; set; }
        public string LOCATION_LATITUDE { get; set; }
        public string SERVICE_AREA { get; set; }
        public string STORE_CONTENT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSP2_RSM_STOCK_DETAIL> DSP2_RSM_STOCK_DETAIL { get; set; }
    }
}
