//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_THBBOBEALT
    {
        public int THBBOBEALT_ID { get; set; }
        public string IDENTIFIER { get; set; }
        public string SENDER { get; set; }
        public Nullable<System.DateTime> SENT { get; set; }
        public string STATUS { get; set; }
        public string MSGTYPE { get; set; }
        public string SOURCE { get; set; }
        public string SCOPE { get; set; }
        public string RESTRICTION { get; set; }
        public string ADDRESSES { get; set; }
        public string CODE { get; set; }
        public string NOTE { get; set; }
        public string REFERENCE { get; set; }
        public string INCIDENTS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
