//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_EXTRAININFO
    {
        public int EXTRAININFO_ID { get; set; }
        public Nullable<int> EXTRAINALT_ID { get; set; }
        public string LANGUAGE { get; set; }
        public string CATEGORY { get; set; }
        public string EVENT { get; set; }
        public string RESPONSETYPE { get; set; }
        public string URGENCY { get; set; }
        public string SEVERITY { get; set; }
        public string CERTAINTY { get; set; }
        public string AUDIENCE { get; set; }
        public string EVENTCODENAME { get; set; }
        public string EVENTCODEVALUE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE { get; set; }
        public Nullable<System.DateTime> ONSET { get; set; }
        public Nullable<System.DateTime> EXPIRES { get; set; }
        public string SENDERNAME { get; set; }
        public string HEADLINE { get; set; }
        public string DESCRIPTION { get; set; }
        public string INSTRUCTION { get; set; }
        public string WEB { get; set; }
        public string ALERT_TITLE { get; set; }
        public string SEVERITY_LEVEL { get; set; }
        public string ALERT_COLOR { get; set; }
        public string WEBSITE_COLOR { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
