//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_THSRCAREA
    {
        public int THSRCAREA_ID { get; set; }
        public Nullable<int> THSRCINFO_ID { get; set; }
        public string AREADESC { get; set; }
        public string CIRCLE1 { get; set; }
        public string CIRCLE2 { get; set; }
        public string CIRCLE3 { get; set; }
        public string CIRCLE4 { get; set; }
        public string CIRCLE5 { get; set; }
        public string CIRCLE6 { get; set; }
        public string CIRCLE7 { get; set; }
        public string CIRCLE8 { get; set; }
        public string CIRCLE9 { get; set; }
        public string CIRCLE10 { get; set; }
        public string CIRCLE11 { get; set; }
        public string CIRCLE12 { get; set; }
        public string CIRCLE13 { get; set; }
        public string CIRCLE14 { get; set; }
        public string CIRCLE15 { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
