//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_WS_PACKAGE
    {
        public int WG_ID { get; set; }
        public string WG_SYSCODE { get; set; }
        public string WG_NAME { get; set; }
        public string WG_ORG { get; set; }
        public string WG_CONTACT { get; set; }
        public string WG_TEL { get; set; }
        public string WG_URL { get; set; }
        public string WG_INPDESC { get; set; }
        public string WG_OUPDESC { get; set; }
        public string WG_FUNCDESC { get; set; }
        public bool WG_AUTH { get; set; }
        public bool WG_STATE { get; set; }
        public bool WG_ISOPEN { get; set; }
        public string WG_FAILED_EMAIL { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
