//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_LOCATION_MASTER
    {
        public int LOCATION_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string LOCATION_ADDRESS { get; set; }
        public string LOCATION_COORDINATE_X { get; set; }
        public string LOCATION_COORDINATE_Y { get; set; }
        public string LOCATION_LONGITUDE { get; set; }
        public string LOCATION_LATITUDE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TITLE { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_EXT { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public System.Data.Entity.Spatial.DbGeography GEO { get; set; }
    }
}
