//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_RESOURCE_STOCK_RECORD
    {
        public int RESOURCE_RECORD_ID { get; set; }
        public int RESOURCE_STOCK_ID { get; set; }
        public int RESOURCE_ID { get; set; }
        public int UNIT_LOCATION_ID { get; set; }
        public System.DateTime CHECK_DATE { get; set; }
        public int LAST_CURRENT_QTY { get; set; }
        public int CURRENT_QTY { get; set; }
        public int AVAILABLE_QTY { get; set; }
        public Nullable<int> DIFFERENT_QTY { get; set; }
        public string DIFF_REASON_CODE { get; set; }
        public string REMARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
