//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDD2_AUDTING_RECORD
    {
        public int AUDITING_RECORD_ID { get; set; }
        public int AUDITING_ID { get; set; }
        public int UNIT_ID { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public System.DateTime SEND_DATE { get; set; }
        public string RECIPIENT { get; set; }
        public string EMAIL { get; set; }
        public string OPERATION_TITLE { get; set; }
        public string OPERATION_CONTENT { get; set; }
        public string OPERATION_RESULT { get; set; }
        public string OPERATION_RESULT_DESC { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
