//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEA2_EVACUATE_AREA
    {
        public decimal EVACUATE_AREA_ID { get; set; }
        public string CITY_ID { get; set; }
        public string TOWN_ID { get; set; }
        public string VILLAGE_ID { get; set; }
        public string NEIGHBOR { get; set; }
        public Nullable<System.DateTime> EVACUATEDATE_S { get; set; }
        public Nullable<System.DateTime> EVACUATEDATE_E { get; set; }
        public string DEBRIS_NO { get; set; }
        public string ALERT_TYPE { get; set; }
        public Nullable<System.DateTime> ALERT_TIME { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> OLD_ID { get; set; }
    }
}
