//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEA2_SHELTER_REPORT
    {
        public decimal SHELTER_REPORT_ID { get; set; }
        public Nullable<decimal> SHELTER_STATUS_ID { get; set; }
        public Nullable<decimal> SHELTER_ID { get; set; }
        public string PRJ_NO { get; set; }
        public decimal RESIDENT_ID { get; set; }
        public string CHECKIN_CODE { get; set; }
        public Nullable<System.DateTime> CHECKIN_TIME { get; set; }
        public Nullable<System.DateTime> CHECKOUT_TIME { get; set; }
        public string CHECKOUT_REASON { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> OLD_ID { get; set; }
    }
}
