//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEA2_CONTACTS
    {
        public decimal CONTACT_ID { get; set; }
        public string CITY_ID { get; set; }
        public string TOWN_ID { get; set; }
        public string VILLAGE_ID { get; set; }
        public string ADDR { get; set; }
        public string CONTACT_NAME { get; set; }
        public string MOBILE { get; set; }
        public string UNIT_NAME { get; set; }
        public string UNIT_CITY_ID { get; set; }
        public string UNIT_TOWN_ID { get; set; }
        public string UNIT_VILLAGE_ID { get; set; }
        public string UNIT_ADDR { get; set; }
        public string TITLE { get; set; }
        public string TELEPHONE { get; set; }
        public string WGS84_PTS { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> OLD_ID { get; set; }
    }
}
