//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEA2_MAPINFO
    {
        public decimal MAP_ID { get; set; }
        public string MAPTITLE { get; set; }
        public string MAPNUMBER { get; set; }
        public string COUNTY { get; set; }
        public string TOWN { get; set; }
        public string VILLAGE { get; set; }
        public Nullable<int> VILLAGEAREA { get; set; }
        public Nullable<int> VILLAGEPOPUL { get; set; }
        public string CENAME { get; set; }
        public string CEADRR { get; set; }
        public string CEPHONE { get; set; }
        public string TENAME { get; set; }
        public string TEADDR { get; set; }
        public string TEPHONE { get; set; }
        public string THNAME { get; set; }
        public string THADDR { get; set; }
        public string THPHONE { get; set; }
        public string PDNAME { get; set; }
        public string PDADDR { get; set; }
        public string PDPHONE { get; set; }
        public string FDNAME { get; set; }
        public string FDADDR { get; set; }
        public string FDPHONE { get; set; }
        public string NAME1 { get; set; }
        public string PHONE1 { get; set; }
        public string NAME2 { get; set; }
        public string PHONE2 { get; set; }
        public string HELILOCNAME { get; set; }
        public string HELILOCADDR { get; set; }
        public string HELILOCPHONE { get; set; }
        public string MAPMAKER { get; set; }
        public Nullable<System.DateTime> MAPYYMM { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
