//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EVENT_VISITOR
    {
        public decimal VISITOR_UID { get; set; }
        public decimal LIST_UID { get; set; }
        public System.DateTime VIS_TIME { get; set; }
        public System.DateTime LEV_TIME { get; set; }
        public string VIS_NAT { get; set; }
        public string VIS_ECO { get; set; }
        public string VIS_RESON { get; set; }
        public Nullable<int> VIS_NUM { get; set; }
        public string REP_MEM_NAME { get; set; }
        public string REC_MEM_POS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EEM2_EVENT_LIST EEM2_EVENT_LIST { get; set; }
    }
}
