//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_BOARD_BASE
    {
        public decimal ITEM_UID { get; set; }
        public string RPT_VERSION { get; set; }
        public Nullable<int> SHOW_ORDER { get; set; }
        public string ITEM_NAME { get; set; }
        public string DEFAULT_CONTENT { get; set; }
        public string SORUCE_FROM { get; set; }
        public decimal ORG_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> ORG_ID_OLD { get; set; }
    }
}
