//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EVENT_SUPPORT
    {
        public decimal SUPPORT_UID { get; set; }
        public decimal LIST_UID { get; set; }
        public Nullable<System.DateTime> SURPPORT_ST_TIME { get; set; }
        public Nullable<System.DateTime> SURPPORT_END_TIME { get; set; }
        public string SURPPORT_COUNTRY { get; set; }
        public string LEADER_NAME { get; set; }
        public string LEADER_TITLE { get; set; }
        public Nullable<int> TEAM_NUM { get; set; }
        public Nullable<int> SEARCH_DOG_NUM { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_UNIT { get; set; }
        public string SURPPORT_DIS { get; set; }
        public string SURPPOT_DESCRIPTION { get; set; }
        public string EQU_DESCRIPTION { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EEM2_EVENT_LIST EEM2_EVENT_LIST { get; set; }
    }
}
