//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EOC_PRJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_EOC_PRJ()
        {
            this.EEM2_EOC_PRJ_HISTORY = new HashSet<EEM2_EOC_PRJ_HISTORY>();
            this.EEM2_EVENT_LIST = new HashSet<EEM2_EVENT_LIST>();
            this.EEM2_RELEASE_DATA = new HashSet<EEM2_RELEASE_DATA>();
        }
    
        public decimal PRJ_NO { get; set; }
        public string EOC_ID { get; set; }
        public decimal PRJ_GROUP_UID { get; set; }
        public string CASE_NAME { get; set; }
        public decimal DIS_DATA_UID { get; set; }
        public System.DateTime PRJ_STIME { get; set; }
        public Nullable<System.DateTime> PRJ_ETIME { get; set; }
        public string OPEN_LV { get; set; }
        public Nullable<System.DateTime> DIS_CNT_STIME { get; set; }
        public Nullable<System.DateTime> DIS_CNT_ETIME { get; set; }
        public string CMMAND_NAME { get; set; }
        public string CMMAND_TITLE { get; set; }
        public string CAUSE { get; set; }
        public string DISASTER { get; set; }
        public string MEMO_S { get; set; }
        public string SOURCE_CASE_KEY { get; set; }
        public string OPENER_NAME { get; set; }
        public string OPENER_ORG { get; set; }
        public string OPENER_TEL { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> EOC_ID_OLD { get; set; }
        public Nullable<decimal> PRJ_NO_OLD { get; set; }
        public Nullable<decimal> PRJ_GROUP_UID_OLD { get; set; }
    
        public virtual EEM2_DIS_DATA EEM2_DIS_DATA { get; set; }
        public virtual EEM2_EOC_DATA EEM2_EOC_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EOC_PRJ_HISTORY> EEM2_EOC_PRJ_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_LIST> EEM2_EVENT_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_RELEASE_DATA> EEM2_RELEASE_DATA { get; set; }
    }
}
