//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_WORK_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_WORK_MAIN()
        {
            this.EEM2_WORK_FILE = new HashSet<EEM2_WORK_FILE>();
            this.EEM2_WORK_ITEM = new HashSet<EEM2_WORK_ITEM>();
        }
    
        public decimal WORK_CODE { get; set; }
        public decimal PRJ_NO { get; set; }
        public string COMMANDER { get; set; }
        public string MEETING_TYPE { get; set; }
        public string NAME { get; set; }
        public System.DateTime WK_MEET_TIME { get; set; }
        public Nullable<System.DateTime> NEX_MEET_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string WORK_CODE_OLD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_WORK_FILE> EEM2_WORK_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_WORK_ITEM> EEM2_WORK_ITEM { get; set; }
    }
}
