//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EOC_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_EOC_GROUP()
        {
            this.EEM2_EOC_GROUP_ORG = new HashSet<EEM2_EOC_GROUP_ORG>();
            this.EEM2_EOC_GROUP_ORG1 = new HashSet<EEM2_EOC_GROUP_ORG>();
        }
    
        public decimal EOC_GROUP_UID { get; set; }
        public string EOC_ID { get; set; }
        public string GROUP_N1 { get; set; }
        public string GROUP_N2 { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public Nullable<decimal> EOC_ID_OLD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EOC_GROUP_ORG> EEM2_EOC_GROUP_ORG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EOC_GROUP_ORG> EEM2_EOC_GROUP_ORG1 { get; set; }
    }
}
