//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_NEWS_INVEST
    {
        public decimal NEWS_INVEST_UID { get; set; }
        public decimal NEWS_UID { get; set; }
        public string RESULT { get; set; }
        public string INVESTIGATOR { get; set; }
        public string DIM_CHIEF { get; set; }
        public string IS_PRESENT { get; set; }
        public string IS_NEWS_UPDATE { get; set; }
        public string IS_SEND_NEWS_GROUP { get; set; }
        public string NEWS_GROUP_RECEIVER { get; set; }
        public Nullable<System.DateTime> NEWS_GROUP_RECEIVE_TIME { get; set; }
        public string IS_COPY_AND_SEND { get; set; }
        public string IS_OTHER { get; set; }
        public string OTHER_DESCRIPTION { get; set; }
        public string DISASTER_CHIEF { get; set; }
        public string OP_CHIEF { get; set; }
        public string AUDIT_COMMANDER { get; set; }
        public string APPROVE_COMMANDER { get; set; }
        public string COMMANDER_APPROVE_CONTENT { get; set; }
        public string MEMO_M { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
