//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_WORK_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_WORK_ITEM()
        {
            this.EEM2_WORK_ITEM_ORG = new HashSet<EEM2_WORK_ITEM_ORG>();
        }
    
        public decimal WORK_ITEM_UID { get; set; }
        public decimal WORK_CODE { get; set; }
        public string WORK_ITEM { get; set; }
        public System.DateTime SUB_TIME { get; set; }
        public string MEMO_S { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_WORK_ITEM_ORG> EEM2_WORK_ITEM_ORG { get; set; }
        public virtual EEM2_WORK_MAIN EEM2_WORK_MAIN { get; set; }
    }
}
