//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_RELEASE_DATA
    {
        public decimal NEWS_DATA_UID { get; set; }
        public decimal PRJ_NO { get; set; }
        public System.DateTime POST_TIME { get; set; }
        public string CONTACT { get; set; }
        public string CONTACT_TEL { get; set; }
        public string TOPIC { get; set; }
        public string CONTENT { get; set; }
        public string ATT_FILE_NAME { get; set; }
        public string ATT_FILE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EEM2_EOC_PRJ EEM2_EOC_PRJ { get; set; }
    }
}
