//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_NEWS_TRANSFER
    {
        public decimal NEWS_TRANS_UID { get; set; }
        public decimal NEWS_UID { get; set; }
        public string TRANS_UNITNAME { get; set; }
        public string TRANS_TYPE { get; set; }
        public string POWERNAME { get; set; }
        public Nullable<System.DateTime> POWERTIME { get; set; }
        public string UNITPROCSITU { get; set; }
        public Nullable<System.DateTime> STRANTIME { get; set; }
        public Nullable<System.DateTime> ANSWERTIME { get; set; }
        public string ANSER_PERSON { get; set; }
        public string RECIVMAN { get; set; }
        public string TASK_NO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
