//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_EVENT_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_EVENT_LIST()
        {
            this.EEM2_EVENT_COMM = new HashSet<EEM2_EVENT_COMM>();
            this.EEM2_EVENT_OTHER = new HashSet<EEM2_EVENT_OTHER>();
            this.EEM2_EVENT_PHONE = new HashSet<EEM2_EVENT_PHONE>();
            this.EEM2_EVENT_SUPPORT = new HashSet<EEM2_EVENT_SUPPORT>();
            this.EEM2_EVENT_VISITOR = new HashSet<EEM2_EVENT_VISITOR>();
        }
    
        public decimal LIST_UID { get; set; }
        public decimal PRJ_NO { get; set; }
        public string TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        public virtual EEM2_EOC_PRJ EEM2_EOC_PRJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_COMM> EEM2_EVENT_COMM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_OTHER> EEM2_EVENT_OTHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_PHONE> EEM2_EVENT_PHONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_SUPPORT> EEM2_EVENT_SUPPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_EVENT_VISITOR> EEM2_EVENT_VISITOR { get; set; }
    }
}
