//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEM2_NEWS_WATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EEM2_NEWS_WATCH()
        {
            this.EEM2_NEWS_MERGE_REC = new HashSet<EEM2_NEWS_MERGE_REC>();
        }
    
        public decimal NEWS_UID { get; set; }
        public decimal PRJ_NO { get; set; }
        public decimal NEWS_CHANNEL_UID { get; set; }
        public Nullable<System.DateTime> NEWS_REPORT_TIME { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string DIM_TYPE { get; set; }
        public string NEWS_NAME { get; set; }
        public string CONTENT { get; set; }
        public string WATCHER { get; set; }
        public string CHIEF_WATCHER { get; set; }
        public Nullable<System.DateTime> REPORT_TIME { get; set; }
        public string ATT_FILE_NAME { get; set; }
        public string ATT_FILE_ID { get; set; }
        public string DIM_CODE { get; set; }
        public string CASE_STATUS { get; set; }
        public string DISASTER_STATUS { get; set; }
        public string TASK_STATUS { get; set; }
        public string DSP_FILE_ID { get; set; }
        public string DSP_DEL_MARK { get; set; }
        public Nullable<decimal> MERGE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEM2_NEWS_MERGE_REC> EEM2_NEWS_MERGE_REC { get; set; }
    }
}
