//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP2_MENU_TREE
    {
        public int MENU_ID { get; set; }
        public string MENU_INDEX { get; set; }
        public string MENU_NAME { get; set; }
        public string CATEGORY { get; set; }
        public string SHOW_ORDER { get; set; }
        public string FUNCTION_CODE { get; set; }
        public Nullable<int> PARENT_MENU_ID { get; set; }
        public string SYS_CODE { get; set; }
        public string EOC_LEVEL { get; set; }
        public string TYPE { get; set; }
        public string IS_ON_OFF { get; set; }
        public string CREATED_USER { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string ICON_NAME { get; set; }
    }
}
