//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_RPT_MAIN
    {
        public int RPT_MAIN_ID { get; set; }
        public long PRJ_NO { get; set; }
        public string EOC_ID { get; set; }
        public string ORG_NAME { get; set; }
        public int RPT_DEF_ID { get; set; }
        public string RPT_CODE { get; set; }
        public string RPT_APPROVAL { get; set; }
        public string RPT_PHONE { get; set; }
        public string RPT_MOBILE_PHONE { get; set; }
        public Nullable<System.DateTime> RPT_TIME { get; set; }
        public string RPT_USER { get; set; }
        public Nullable<int> RPT_NO { get; set; }
        public string RPT_CONFIRM { get; set; }
        public string CREATED_USER { get; set; }
        public string CREATED_USER_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public string MODIFIED_USER_NAME { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
