//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_ATMP_D3a
    {
        public int ATMP_DETAIL_ID { get; set; }
        public int ATMP_REC_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string SHELTER { get; set; }
        public string OPEN_DATETIME { get; set; }
        public string CLOSE_DATETIME { get; set; }
        public Nullable<int> REFUGEE { get; set; }
        public Nullable<int> REFUGEE_M { get; set; }
        public Nullable<int> REFUGEE_F { get; set; }
        public Nullable<int> REFUGEE_TOTAL { get; set; }
        public Nullable<int> REFUGEE_TOTAL_M { get; set; }
        public Nullable<int> REFUGEE_TOTAL_F { get; set; }
        public Nullable<int> LAST_REFUGEE_TOTAL { get; set; }
        public Nullable<int> SUPPLY_PEOPLE { get; set; }
        public Nullable<int> SUPPLY_DAY { get; set; }
        public string KEEP_SUPPLY { get; set; }
        public string CONTACT { get; set; }
        public string CONTACT_PHONE { get; set; }
        public Nullable<int> PEOPLE_NO { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
