//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_RPT_H1_S
    {
        public int RPT_DETAIL_ID { get; set; }
        public int RPT_MAIN_ID { get; set; }
        public Nullable<System.DateTime> INPUT_DATETIME { get; set; }
        public Nullable<int> MILITARY_CASES { get; set; }
        public Nullable<int> AIRBORNE_CASES { get; set; }
        public Nullable<int> MILITARY_SUPPLY { get; set; }
        public Nullable<int> AIRBORNE_SUPPLY { get; set; }
        public Nullable<int> MILITARY_TRANSPORT { get; set; }
        public Nullable<int> AIRBORNE_TRANSPORT { get; set; }
        public Nullable<int> MILITARY_INJURED { get; set; }
        public Nullable<int> AIRBORNE_INJURED { get; set; }
        public Nullable<int> MILITARY_SURVEY { get; set; }
        public Nullable<int> AIRBORNE_SURVEY { get; set; }
        public Nullable<int> MILITARY_DEAD { get; set; }
        public Nullable<int> AIRBORNE_DEAD { get; set; }
        public Nullable<int> MILITARY_WORKERS { get; set; }
        public Nullable<int> AIRBORNE_WORKERS { get; set; }
        public Nullable<int> MILITARY_FLIGHTS { get; set; }
        public Nullable<int> AIRBORNE_FLIGHTS { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
