//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA2_ATMP_F1a
    {
        public int ATMP_DETAIL_ID { get; set; }
        public int ATMP_REC_ID { get; set; }
        public string TRFSTATUS { get; set; }
        public string ROADTYPE_ID { get; set; }
        public string ROAD_ID { get; set; }
        public Nullable<decimal> STARTMILE { get; set; }
        public Nullable<decimal> STARTPLUS { get; set; }
        public Nullable<decimal> ENDMILE { get; set; }
        public Nullable<decimal> ENDPLUS { get; set; }
        public string LINECODE { get; set; }
        public string CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string TOWN_ID { get; set; }
        public string TOWN_NAME { get; set; }
        public string ADDNAME { get; set; }
        public string WGS84_X { get; set; }
        public string WGS84_Y { get; set; }
        public string WGS84_X_SCTL { get; set; }
        public string WGS84_Y_SCTL { get; set; }
        public string WGS84_X_ECTL { get; set; }
        public string WGS84_Y_ECTL { get; set; }
        public string CLOSE_TYPE { get; set; }
        public string CLOSE_TSUB { get; set; }
        public string CLOSE_DATETIME { get; set; }
        public Nullable<int> REPAIRE_DAY { get; set; }
        public string CLOSE_TEXT { get; set; }
        public string REPAIRE_TEXT { get; set; }
        public string ALT_ROUTE { get; set; }
        public Nullable<int> BUILD_COST { get; set; }
        public string OPEN_TEXT { get; set; }
        public string OPEN_DATETIME { get; set; }
        public string REMARK { get; set; }
        public string BRG_CLOSE { get; set; }
        public string NO_DATA_MARK { get; set; }
        public string CASE_NO { get; set; }
        public string DATA_SOURCE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
