//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS2_STAY_HERE
    {
        public decimal STAYHERE_SEQNO { get; set; }
        public string PERSON_NAME { get; set; }
        public string PERSON_IDNO { get; set; }
        public string PERSON_SEX { get; set; }
        public Nullable<decimal> BIRTHDAY_YEAR { get; set; }
        public string LIVE_COUNTY { get; set; }
        public string LIVE_TOWN { get; set; }
        public string LIVE_VILLAGE { get; set; }
        public string LIVE_STREET { get; set; }
        public string PERSON_PHONE { get; set; }
        public string LAST_COUNTY { get; set; }
        public string LAST_TOWN { get; set; }
        public string LAST_VILLAGE { get; set; }
        public string LAST_STREET { get; set; }
        public string COORDINATE_X { get; set; }
        public string COORDINATE_Y { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public byte[] PERSON_PHOTO { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public decimal STARTUP_SEQNO { get; set; }
        public decimal LOGIN_SEQNO { get; set; }
        public string CITIZENSHIP { get; set; }
        public string LOGIN_PERSON_EMAIL { get; set; }
        public string PERSON_SITU { get; set; }
        public string PERSON_MSG { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_ID { get; set; }
    }
}
