//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTS_FU_META
    {
        public int FM_ID { get; set; }
        public string FM_TITLE { get; set; }
        public string FM_PATH { get; set; }
        public string FM_KEYWORD { get; set; }
        public string FM_AUTHOR { get; set; }
        public string FM_DESC { get; set; }
        public Nullable<System.DateTime> FM_CREATED_TIME { get; set; }
        public string FM_DATA_TYPE { get; set; }
        public string FM_SOURCE { get; set; }
        public string FM_AUTHORITY { get; set; }
        public string FM_ADDR1 { get; set; }
        public string FM_ADDR2 { get; set; }
        public string FM_ADDR3 { get; set; }
        public string FM_GEOGRAPHY { get; set; }
        public Nullable<int> FM_VERSION { get; set; }
    }
}
