//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDS2_DESCRIPTION
    {
        public int MAIN_ID { get; set; }
        public string EOC_ID { get; set; }
        public long PRJ_NO { get; set; }
        public string CATEGORY { get; set; }
        public string CITIZENSHIP { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string OCCUR_TYPE { get; set; }
        public Nullable<System.DateTime> OCCUR_TIME { get; set; }
        public string CITY_TYPE { get; set; }
        public string CITY_ID { get; set; }
        public string TOWN_ID { get; set; }
        public string ADDR_FULL { get; set; }
        public string WGS84 { get; set; }
        public string AREA_LV1 { get; set; }
        public string AREA_LV2 { get; set; }
        public string AREA_LV3 { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> AGE { get; set; }
        public string CASUALTIES { get; set; }
        public string CASUALTIES_LV1 { get; set; }
        public string CASUALTIES_LV2 { get; set; }
        public string CASUALTIES_LV3 { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public int DETAIL_ID { get; set; }
        public string NAME { get; set; }
        public string MEMO_S { get; set; }
    }
}
