//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTT2_COMMLIST_11
    {
        public int COMMLIST_MAIN_ID { get; set; }
        public string OPERATOR_ID { get; set; }
        public string EOC_ID { get; set; }
        public string OPERATOR_NAME { get; set; }
        public string OPERATOR_TITLE { get; set; }
        public string OPERATOR_TEL_NO { get; set; }
        public string OPERATOR_EXT_NO { get; set; }
        public string OPERATOR_MOBILE_NO { get; set; }
        public string OPERATOR_EMAIL { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public int COMMLIST_DETAIL_ID { get; set; }
    }
}
