//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTT2_BULLETIN_10
    {
        public long PRJ_NO { get; set; }
        public string TRANSFER_EOC { get; set; }
        public System.DateTime TRANSFER_TIME { get; set; }
        public string EOC_OPEN_TIER { get; set; }
        public string BULLETIN_TITLE { get; set; }
        public string BULLETIN_FILE { get; set; }
        public string RESPONSE_CODE { get; set; }
        public int RESPONSE_LIMIT { get; set; }
        public string SIGN_LEVEL { get; set; }
        public string BULLETIN_USER { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public Nullable<System.DateTime> UPLOAD_RETURN_TIME { get; set; }
        public Nullable<int> BULLETIN_COUNT { get; set; }
        public Nullable<int> RECEIVE_COUNT { get; set; }
        public Nullable<int> RESPONSE_COUNT { get; set; }
        public Nullable<System.DateTime> BULLETIN_CLOSE_TIME { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string RESPONSE_SCAN_FILE { get; set; }
        public long BULLETIN_MAIN_ID { get; set; }
    }
}
