//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTT2_PARAMETR_00
    {
        public string PARAMETER_CODE { get; set; }
        public string EOC_ID { get; set; }
        public System.DateTime PARAMETER_STR_DATE { get; set; }
        public Nullable<System.DateTime> PARAMETER_END_DATE { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string PARAMETER_REMARK { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public int PAR_MAIN_ID { get; set; }
    }
}
