//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPD_METADATA
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DATA_PROVIDER { get; set; }
        public string RESOURCE_FIELD { get; set; }
        public string LICENSE { get; set; }
        public string NOTES { get; set; }
        public string LICENSE_URL { get; set; }
        public string UPDATE_FREQUENCY { get; set; }
        public string COST { get; set; }
        public string RESOURCE_FORMAT { get; set; }
        public string RESOURCE_DOWNLOAD_URL { get; set; }
        public string PUBLISHER_OID { get; set; }
        public string PUBLISHER_CONTACT_NAME { get; set; }
        public string PUBLISHER_CONTACT_PHONE { get; set; }
        public string SPATIAL_COVERAGE { get; set; }
        public string LANGUAGE { get; set; }
        public string CATEGORY_DATASET { get; set; }
        public string KEYWORD { get; set; }
        public string COVERAGE_STARTED_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
    }
}
