//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_ID_MAPPING
    {
        public decimal EOC_ID { get; set; }
        public string ORG_FULL_TITLE { get; set; }
        public decimal ORG_ID_OLD { get; set; }
        public string OID { get; set; }
        public string ORG_ID { get; set; }
    }
}
